#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the $wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

PROJECT_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$PROJECT_ROOT"

for required_command in gh jq op shasum; do
  if ! command -v "$required_command" >/dev/null 2>&1; then
    printf 'Required command not found: %s\n' "$required_command" >&2
    exit 1
  fi
done

credential_json() {
  jq --arg title "$OP_ITEM_TITLE" \
    --arg client_id "$APP_CLIENT_ID" \
    --rawfile private_key "$PRIVATE_KEY_PATH" '
      if ([.fields[] | select(.id == "username")] | length) != 1 or
         ([.fields[] | select(.id == "credential")] | length) != 1
      then error("API Credential template is missing username or credential")
      else
        .title = $title
        | .tags = ((.tags // []) + ["ci-cd", "codex-cost-meter", "github-app"] | unique)
        | (.fields[] | select(.id == "username")) |=
            (.label = "Client ID" | .type = "STRING" | .value = $client_id)
        | (.fields[] | select(.id == "credential")) |=
            (.label = "Private Key" | .type = "CONCEALED" | .value = $private_key)
      end
    '
}

banner "Codex Cost Meter · Homebrew PR App"

stage "GitHub App — register"
say "Create a private App that can push one automation branch and open its PR."
open_url "https://github.com/settings/apps/new"
step "Use a unique App name such as 'codex-cost-meter-homebrew-pr'."
step "Set Homepage URL to https://github.com/deinspanjer/codex-cost-meter."
step "Under Identifying and authorizing users, do not add a Redirect URI. If a blank Redirect URI row is present, select Delete."
step "Clear Expire user authorization tokens, and leave Request user authorization (OAuth) during installation and Enable Device Flow unchecked. This App does not authorize users."
step "Under Post installation, leave Setup URL blank and Redirect on update unchecked."
step "Disable the webhook; this App does not receive events."
step "Under Repository permissions, set Contents and Pull requests to Read and write. Leave every other configurable permission at No access."
step "Choose 'Only on this account' under Where can this GitHub App be installed, then create the App."
step "On the App's General page, copy its Client ID."
ask APP_CLIENT_ID "Paste the Client ID:"
if [[ -z "$APP_CLIENT_ID" ]]; then
  printf 'Client ID is required.\n' >&2
  exit 1
fi

stage "GitHub App — private key"
say "Generate the JWT-signing private key; GitHub downloads it as a PEM file."
step "On the App's General page, scroll to Private keys and select Generate a private key."
step "Wait for the .pem file to finish downloading."
ask PRIVATE_KEY_PATH "Enter the downloaded PEM path:"
if [[ "$PRIVATE_KEY_PATH" == "~/"* ]]; then
  PRIVATE_KEY_PATH="${HOME}/${PRIVATE_KEY_PATH:2}"
fi
if [[ ! -f "$PRIVATE_KEY_PATH" || ! -r "$PRIVATE_KEY_PATH" ]]; then
  printf 'Private key is not a readable file: %s\n' "$PRIVATE_KEY_PATH" >&2
  exit 1
fi
if [[ $(wc -c < "$PRIVATE_KEY_PATH") -gt 65536 ]] ||
   ! grep -Eq '^-----BEGIN (RSA )?PRIVATE KEY-----$' "$PRIVATE_KEY_PATH" ||
   ! grep -Eq '^-----END (RSA )?PRIVATE KEY-----$' "$PRIVATE_KEY_PATH"; then
  printf 'File does not look like a bounded PEM private key.\n' >&2
  exit 1
fi

stage "1Password — API Credential"
say "Store the recoverable private key in 1Password without exposing it in arguments or output."
if ! op account list >/dev/null 2>&1; then
  warn "1Password CLI is not connected to an unlocked account."
  open_url "https://developer.1password.com/docs/cli/app-integration/"
  step "Unlock 1Password and enable Settings → Developer → Integrate with 1Password CLI, or sign in with op."
  pause "Press Enter after 1Password CLI access is ready."
fi
if ! op account list >/dev/null 2>&1; then
  printf '1Password CLI is still unavailable.\n' >&2
  exit 1
fi
say "Available vaults:"
op vault list --format json | jq -r '.[] | "  - \(.name)"'
ask OP_VAULT "Enter the destination vault name or ID:"
op vault get "$OP_VAULT" >/dev/null
OP_ITEM_TITLE="Codex Cost Meter Homebrew PR GitHub App"
if op item get "$OP_ITEM_TITLE" --vault "$OP_VAULT" >/dev/null 2>&1; then
  if ! confirm "Replace the existing API Credential with this Client ID and private key?"; then
    printf 'Existing 1Password credential was not changed.\n' >&2
    exit 1
  fi
  OP_ITEM_ID=$(
    op item get "$OP_ITEM_TITLE" --vault "$OP_VAULT" --format json --reveal |
      credential_json |
      op item edit "$OP_ITEM_TITLE" --vault "$OP_VAULT" --format json |
      jq -r .id
  )
else
  OP_ITEM_ID=$(
    op item template get "API Credential" |
      credential_json |
      op item create --vault "$OP_VAULT" --format json - |
      jq -r .id
  )
fi
if [[ -z "$OP_ITEM_ID" || "$OP_ITEM_ID" == null ]]; then
  printf '1Password did not return a credential item ID.\n' >&2
  exit 1
fi
local_key_sha=$(shasum -a 256 "$PRIVATE_KEY_PATH" | awk '{print $1}')
stored_key_sha=$(
  op item get "$OP_ITEM_ID" --vault "$OP_VAULT" --format json --reveal |
    jq -j '.fields[] | select(.id == "credential") | .value' |
    shasum -a 256 |
    awk '{print $1}'
)
if [[ "$stored_key_sha" != "$local_key_sha" ]]; then
  printf '1Password private-key verification failed.\n' >&2
  exit 1
fi
say "Verified 1Password API Credential $OP_ITEM_ID."

stage "GitHub App — install"
say "Limit the App installation to this repository."
open_url "https://github.com/settings/apps"
step "Open the App, select Install App in its sidebar, and choose the deinspanjer account."
step "Choose Only select repositories, select codex-cost-meter, then install."
if ! confirm "Is the App installed only on deinspanjer/codex-cost-meter?"; then
  printf 'Install the App before continuing.\n' >&2
  exit 1
fi

stage "Repository — configure"
say "Copy the public Client ID and private PEM into their exact Actions names."
set_var HOMEBREW_PR_APP_CLIENT_ID "$APP_CLIENT_ID"
PRIVATE_KEY=$(< "$PRIVATE_KEY_PATH")
set_secret HOMEBREW_PR_APP_PRIVATE_KEY "$PRIVATE_KEY"
unset PRIVATE_KEY
configured_client_id=$(gh variable get HOMEBREW_PR_APP_CLIENT_ID --json value --jq .value 2>/dev/null || true)
if [[ "$configured_client_id" != "$APP_CLIENT_ID" ]]; then
  printf 'Repository variable HOMEBREW_PR_APP_CLIENT_ID was not updated.\n' >&2
  exit 1
fi
if [[ "${WRITTEN_SECRET[*]}" != HOMEBREW_PR_APP_PRIVATE_KEY ]] ||
   ! gh secret list --json name --jq '.[].name' | grep -qx HOMEBREW_PR_APP_PRIVATE_KEY; then
  printf 'Repository secret HOMEBREW_PR_APP_PRIVATE_KEY was not updated.\n' >&2
  exit 1
fi
warn "After confirming both copies, remove the downloaded PEM from local disk; 1Password is the recovery copy."

finish
